### ISSUE TITLE
Github Bounty

### ISSUE THREAD

**Issue by IttriumCore** [IttriumCore/ittrium#1]
1. Follow IttriumCore
2. Star our repositories 
3. Post your XIT address below

**Comment by jugi1** [comment]
iUnppo9RtjP1wk1i5j6sYRdL98z9fDcz7S

**Comment by reaLionheart** [comment]
idAxDUYJMjtp7XxR6rSYyiXwiUXcMewyJm

**Comment by Olionkey** [comment]
inyAk1uTkV9Si6xXJ29hjzRNPNVmBL12xT

**Comment by RubberDuckyIsTheOne** [comment]
imqvha7rsbXyRwaQY4viNpaM1b8myjLspP

**Comment by torutoruman** [comment]
ir7D5SJdseoRzgnmsjGcZAwYizySEL2XHW

**Comment by Xenon1005** [comment]
ib1eexLZEu5Us6SfN3S6ESEtBX9xqzUePD

**Comment by mcrex666** [comment]
ie14RJqc21qUroG4C9B5KDuxcCf59T4TeN

**Comment by Vattalus** [comment]
iSwxi6RvrbLwKvCDZmNWf3V1N16Spj22L5

**Comment by Aportic** [comment]
iXUrhGuvGps3Akpaav5Dq8gNkQegXHa9Jg

**Comment by Moramba** [comment]
iStfdpjAeYJsKnaF79iLo7Vu9JorXVSb18

**Comment by junforever** [comment]
iqe33KYwxvhnAnUcVyNhZhKKX7NqG9CHGY

**Comment by AlexeChe1** [comment]
iUtwHNijuDhgndyevjeNKNJDwCKqF5L5Le

**Comment by aburanne** [comment]
iki3DbqH92WTnCbR8BruPqZG7M1YFQnB1U

**Comment by WildWildEast** [comment]
ibQzxNf46gxzmr3PtDzHHBYrq76AjaVu3x

**Comment by Pistascialentiscus** [comment]
idQNX8kWbuf6AfN6Bc9uAxiyny16Kb7bwR

**Comment by ayzabonan** [comment]
ijdwQ3FknXzPbExoeWbx6kYWcbsd2PAEa6

**Comment by Semberin** [comment]
iUQycpeLNH8UjiWyx61jEnaoTjmeixfK4M

**Comment by Hantard** [comment]
iWVxqXHd4UN3pd92bwtYqHuEeMsTHxuK8r

**Comment by hadekedek** [comment]
iWh2Fa5hAs8Wnxp2u5B8PUnoDcbfjSTkTv

**Comment by Hansellemar** [comment]
iqeCfW9tmrMZgNzBHt2G4Xv7uYkGKPVuKV

**Comment by Serabyan** [comment]
iTmyHtJx2wnMfM3C8WstoUsYWjuzXqqqCi

**Comment by Ramtaris** [comment]
iiYXT8KiJCqrmar5frmhAh2hR9SSSGEuHQ

**Comment by Parsimo** [comment]
iaJUy2MUztAKC1jn6YfTaj4kDK1wvp1yyp

**Comment by Trapato** [comment]
iTH9nYTXKRbGyFTnXKG8AjNXpmwNQWhXsC

**Comment by Bombilly** [comment]
imvaEu7NwTtN2yQ8eD6nua8mvt62VCsM7f

**Comment by parspero** [comment]
ihttDX9srhWLqaSp3dTcwf3yAUkqcdb9cc

**Comment by Righteousx** [comment]
igLYt5k4vkYYKvbefHNrAAxepxnrguAgzK

**Comment by mobzik** [comment]
ib3a14oxHQbt4RtUwpLYt8MHjneFhYZUhe

**Comment by moralyano** [comment]
ipLmDL7xM3Bk3RXQWnT7KwERPtdMhfNUEq

**Comment by hisapop** [comment]
iaTyo6iHt1eHt4d1nLomQh9eSGZ4H5cg9d

**Comment by Zabbuo** [comment]
ieR24ak3Y1NjEQmdrFvnBEj7EKZmhKUSqx

**Comment by Vertivar** [comment]
ik2CgGGs9X1Ttrsz7k1KM2Du4mtGr1SCqm

**Comment by Nesfito** [comment]
iqmhQ9y8dLqav3MdDTwCpnokRWzdXozvs2

**Comment by trabji85** [comment]
ipDWC5D8vhe7UtqTFvveFaB4evug7vfwwB

**Comment by rakujoj** [comment]
iWD9w7L5TNw6GEqP3ZJQMJ86yhR495pF4Y

**Comment by serububogu** [comment]
icZWrXP3eyFRUBRpqUettU7TrQGUEaMA42

**Comment by xinova96** [comment]
iqU77wtsihVzy2PctKK9w9m9BdY5fxuBLU

**Comment by rezukabuf** [comment]
ibnwJLMT3kzmZT74CseTJ5FA7ZhJxNmqyU

**Comment by pucifidul** [comment]
ie2ezb9NfUfmfJ7HNmsV9VXWamBxaKSNYw

**Comment by Kadarapu1988** [comment]
idybYwKjupXN9pkJv5rB8JrkWi4reG9B4p

**Comment by mijoyof** [comment]
iqZiugjZhCApouCwfvU1cb2NfVhU47CnzF

**Comment by FeneyapE** [comment]
ikAFn1zmuWAfxPQV4qDu5hBD24ZAKEo3g7

**Comment by salu75** [comment]
idhFCKveTC9TRxjRPMcSJ9xRz7iHRbGpRq

**Comment by pipenaki** [comment]
igxFsBhBgjpTp4RPRongsTW3ar6SvqhwpZ

**Comment by rifipuvip777** [comment]
iTRm3SMPJSAdgUyx8W6SgCPLZer8BJ3KF3

**Comment by LUWavifu** [comment]
ipuJbU5ywn744cTUWu4eb3qY3edKza2HYM

**Comment by zezamafe33** [comment]
ibHKb2EzkLZhEgddiemy5kq5zuR5Pcnafp

**Comment by budumejeke** [comment]
iVEkU9DL3CtiHxSQKtD8SEM19NU2Nr1cDj

**Comment by turoyufeZZZ** [comment]
iW7ccyncUaa9d6fciU3xXbiSyDDTmsdyRL

**Comment by hepugeviku** [comment]
ipmvoxQNwFs5ZkQvC8zKUVzbFRfW8UwGYU

**Comment by badunuguri** [comment]
ii4LaoetEktSVBrVHvtmiwnMMXm3ikdHDL

**Comment by xeyu21** [comment]
ijuJphnx1dpjoGgCqdoxFxxw7cjzd49z5n

**Comment by meru1990** [comment]
inYNndeD9oXd3uj2Ewg5jXut2amRMYMYBj

**Comment by cehiy** [comment]
iig27jQYmopEJzghwR99xBkoSvk7XvN86Q

**Comment by vuyuj5** [comment]
ipk8GoDGAJErkKhgAYkqpxYdXQgef1x87D

**Comment by xevugifi** [comment]
iXNryJbhAhQgTTuKeVRP36H6rmTa3LkuMW

**Comment by IttriumCore** [comment]
Thanks to everyone that contributed to this bounty.  I'm away from my PC for the next few days, so payment wont occur until Sunday.  Apologizes for the inconvenience.

**Comment by goldsunrise** [comment]
ip9qwJWNjgCQ5F3wEGrjKQHNDBa1RTiqKW

**Comment by goldsunrise** [comment]
ip9qwJWNjgCQ5F3wEGrjKQHNDBa1RTiqKW

**Comment by IttriumCore** [comment]
The XIT payment has been sent.
